Repository franciscomorais/flow-libdef, pull requests merged in 2018-09, with the labels that each got.

#1 Initial version
  .babelrc
  .gitignore
  README.md
  bin/commands/index.js
  bin/commands/install.js
  bin/index.js
  package.json
  src/commands/index.js
  src/commands/install.js
  src/index.js
  yarn.lock
Labels: feature

#3 Create utils folder
  src/commands/install.js
  src/utils/index.js
  src/utils/parsers.js
  src/utils/shell-commands.js
Labels: enhancement

#5 Add tests
  .gitignore
  bin/commands/install.js
  bin/locale/index.js
  bin/utils/parsers.js
  package-lock.json
  package.json
  src/commands/install.js
  src/locale/index.js
  src/utils/parsers.js
  test/commands/index.test.js
  test/commands/install.test.js
  test/utils/index.test.js
  test/utils/parsers.test.js
  test/utils/shell-commands.test.js
Labels: enhancement

#7 Update readme with flags
  README.md
Labels: enhancement

#9 Fix package json
  package.json
Labels: bug

#10 Fix my github username
  README.md
Labels: enhancement

#13 Fix files entry in package.json
  package-lock.json
  package.json
Labels: bug

#11 Update README.md
  README.md
Labels: enhancement

#14 Fix shield links
  README.md
Labels: bug
